#Tax amount (decimal)
tax: 0.05
tax-account: tax

#Should we log transactions/creations to Bukkit\Plugins\QuickShop\qs.log?
log-actions: true

shop:
    #Cost to make a stall
    cost: 10
    refund: false
    lock: false
    sneak-only: false
    auto-sign: true
    pay-unlimited-shop-owners: false
    display-items: true
    find-distance: 45

plugins:
    #Whether or not to hook into these plugins, and stop players claiming chests as shops when they can't use the chest.
    preciousstones: true
    worldguard: true
    lockette: true
    griefprevention: true
    residence: true
    towny: true

#List of items to disallow selling of.  Anyone with quickshop.bypass.<itemID> can bypass it    
blacklist:
    - 7