#Tax amount (decimal)
tax: 0.05
tax-account: tax

shop:
    #Cost to make a stall
    cost: 10
    refund: false
    lock: false

plugins:
    #Whether or not to hook into these plugins, and stop players claiming chests as shops when they can't use the chest.
    preciousstones: true
    worldguard: true
    lockette: true
    griefprevention: true