name: QuickShop
version: 0.5
main: org.maxgamer.QuickShop.QuickShop
author: Netherfoam

description: The real shop plugin.
website: http://maxgamer.org
depend: [Vault]
soft-depend: [Towny, PreciousStones, Lockette, WorldGuard, GriefPrevention]

commands:
    qs:
        description: QuickShop command
        usage: /qs unlimited